### ISSUE TITLE
can't use chinese in datasource

### ISSUE THREAD

**Issue by JjiaoLiu** [abdennour/react-csv#10]
const dataSource = [{
    key: '1',
    name: "冰冰",
    age: 32,
    address: "胡迪"
}, {
    key: '2',
    name:"冰冰",
    age: 42,
    address: "胡迪"
}];

const columns = [{
    title: '姓名',
    dataIndex: 'name',
    key: 'name',
}, {
    title: '年龄',
    dataIndex: 'age',
    key: 'age',
}, {
    title: '住址',
    dataIndex: 'address',
    key: 'address',
}];
This is my datasource.
![data](https://cloud.githubusercontent.com/assets/24647907/24576469/f3cf15b6-16ee-11e7-993c-86d640e89190.png)

it does not support chinese?

**Comment by abdennour** [comment]
Did you want to render Chinese headers ? I mean : key, name, age, address .

**Comment by tonylkc** [comment]
@abdennour Hi! I have the same problem that, both header and content have to output in Chinese. However the output is garbled now.

**Comment by JjiaoLiu** [comment]
I can output header in English,no wrong.but I also need to output content in chinese;
![Uploading QQ截图20170405091635.png…]()

**Comment by jiangbing9293** [comment]
使用BOM的方式解决，在数据开始添加  \uFEFF。
修改core.js
encodeURI('data:text/csv;charset=utf-8,\uFEFF' + toCSV(data, headers, separator))
encodeURI(`data:text/csv;charset=utf-8,\uFEFF${toCSV(data, headers, separator)}`)

**Comment by abdennour** [comment]
Thank you @jiangbing9293  for the hint , a new release will be soon accordingly.

**Comment by abdennour** [comment]
Associated NPM 🚚 release is : 1.0.6 . 
________

@JjiaoLiu  @tonylkc  : Please, let me know if it is fixed from your side .

**Comment by estmatic** [comment]
I think that \uFEFF character shouldn't have a comma after it. As it is, I get an extra blank heading, so the column headings and values don't match.

**Comment by JjiaoLiu** [comment]
so cool!
