### ISSUE TITLE
Change CSV file Name?

### ISSUE THREAD

**Issue by ParthPatwalaTA** [abdennour/react-csv#100]
Is there any way to change download file name other than 'generatedBy_react-csv.csv'.
I'm using ```<CSVLink data={csvData} >Download me</CSVLink>``` which will download file directly.

**Comment by rikimaru09** [comment]
You can pass a "filename" prop to changes the file name.

Note: it only works on CSVLink

**Comment by mdsadiq** [comment]
any way to make it work in CSVDownload ?

**Comment by abdennour** [comment]
"filename" props works only with `CSVLink` because it is the `download` attribute of `<a />` tag which is a built-in HTML.
