### ISSUE TITLE
After defining headers the whole column values deleted

### ISSUE THREAD

**Issue by snirlugassy** [abdennour/react-csv#11]
Hey !
I add the const:
`const headers=["CUSTOM", "NOT CUSTOM", "NOT CUSTOM" ..... ]`
By custom i mean different then the json key name, and not custom is exectly as the key name.
later i assigned it into the headers prop
`<CSVLink data={this.props.orders} headers={headers} filename={this.state.orderExportFileName + ".csv"}>`
And in the export the custom headers column values was blank.
How i can set custom headers?

**Comment by abdennour** [comment]
Hi @snirlugassy  , could you log the value of `this.props.orders` & write the console log here ?

**Comment by haroldcb** [comment]
Hello,
I have the same problem, as long as I change the headers, and they are not matching the key value, it only displays the headers without values...
example : const dataTest = [{name:"xxxxxx",firstName:"xxxxxx",email:"xxxxxx@xxxxxx.com"},{name:"xxxxxx",firstName:"xxxxxx",email:"xxxxxx@xxxxxx.com"}];

headers={["Nom","Prenom",,"email"]}

In the result, the 2 first columns are empty, and the email one is good.

**Comment by kevinch** [comment]
Had the same issue. From what i see in the [examples](http://elegance.abdennoor.com/react-csv/) it works only with arrays, not objects:

```
const randomData = Array.from({length:10}, (v, k) =>
  Array.from({length:4}, (vv, kk) => Math.random().toString(36).substring(5))
);
const headers =['Rando-🍌', 'Rando-🍑', 'Rando-🌺', 'Rando-🍀'];
```

I had the same concern and ended up updating my data from objects to arrays.

**Comment by mccabemj** [comment]
@snirlugassy If you are wanting to use custom headers, with names different to the JSON object keys, you can do the following (using @haroldcb example);

```
const headers = [
  { label: 'Nom', key: 'name' },
  { label: 'Prenom', key: 'firstName' },
  { label: 'Email', key: 'email' },
]
```

Does this answer your issue @snirlugassy ?
