### ISSUE TITLE
Can't change filename in CSVDownload

### ISSUE THREAD

**Issue by id247** [abdennour/react-csv#12]
Trying to set another name to file with headers
`
<CSVDownload
  headers={['Content-Disposition: attachment; filename="filename.csv"']}
  data={data}
/>`

It does'n work. 

Is there a way to change the name in CSVDownload?

**Comment by abdennour** [comment]
Filename is only available with `CSVLink` component  and it is used as following : 

```jsx
<CSVLink filename="filename.csv" data={data} headers={headers} />
```

However, attention please ⚠️
`headers` props of `CSVDownload` (or `CSVLink`) is not the HTTP headers , it is an array that contains the first row in the generated css file .


Indeed , `react-csv` works with ready data & it does not make http requests to get data.

Pleas, try to look at the [DEMO site](http://elegance.abdennoor.com/react-csv/)
 namely section which talks about `headers`

#Use case  

```jsx
render() {
const headers = ['name', 'city'];
const data = [['Aleksandr Bazhenov', 'Saint-Petersburg'], ['Abdennour', 'Tunis']] ;
// or data= [{name: 'Aleksandr Bazhenov', city: 'Saint-Petersburg'}, {name: 'Abdennour', city: 'Tunis'}]
return (<CSVDownload filename="filename.csv" data={data} headers={headers} />);

}
```

Assuming now  , your data is not  ready & it needs fetching from API , What we will do ? In, this case , I will not recommend to render `CSVDownload` only when data comes, so your code design can be : 

```jsx
componentDidMount() {

     window.fetch('http://api.domain/users/').then(response => response.json)
         .then(users => {
             this.setState({dataReady: true, data: users });
         })

}
renderWhenDataReady() {
     if (!this.state.dataReady) return null;
    else {
        return <CSVDownload data={this.state.data} />
    }  
}

renderWhenDataNotReady() {
     if (this.state.dataReady) return null;
    else {
        return <i className="fa fa-spin fa-spinner"></i>
    }  
}

render() {

     return (
       <div>
          {this.renderWhenDataReady()}
          {this. renderWhenDataNotReady()}
       </div>
      )

}
```



  
    


@id247  Please, let me know if i can close this issue .

**Comment by id247** [comment]
Thanks for the quick answer.

The issue can be closed.

**Comment by abdennour** [comment]
@id247 , I updated [DEMO site](http://elegance.abdennoor.com/react-csv/) to include a use case of CSVDownload . 

By the way, you can edit the demo directly , so , just replace the value of `iWantToDownload` from `false` to `true` and the download will start.

**Comment by thayronFeitosa** [comment]
the site DEMO it not found
