### ISSUE TITLE
!important is not working on style attribute

### ISSUE THREAD

**Issue by lorenzosjb** [abdennour/react-csv#16]
This line that uses the !important command 
<CSVLink data={data} style={{ color : "#ffffff !important"}}>Export to CSV</CSVLink>

is rendered as 
<a download="generatedBy_react-csv.csv" target="_blank" href="data:text/csv;charset=utf-8,%EF%BB%BF,%22firstname%22,%22lastname%22,%22email%22%0A%22Ahmed%22,%22Tomi%22,%22ah@smthing.co.com%22%0A%22Raed%22,%22Labes%22,%22rl@smthing.co.com%22%0A%22Yezzi%22,%22Min%20l3b%22,%22ymin@cocococo.com%22">Export to CSV</a>

I also tried with the prettyLink example

**Comment by lorenzosjb** [comment]
Tried with using ref workaround but didn´t worked:

<a onClick={this.exportCSVButton.bind(this, this.props.data)} ref={this.important}>Export to CSV</a>

important = node => {
    if (node) {
      node.style.setProperty('color','#ffffff','important');
      node.style.setProperty('padding-left','10px');
    }
  }

**Comment by lorenzosjb** [comment]
Tried with using ref workaround but didn't worked:

<CSVLink data={data} ref={this.important}>Export to CSV</<CSVLink>

important = node => {
    if (node) {
      node.style.setProperty('color','#ffffff','important');
      node.style.setProperty('padding-left','10px');
    }
  }

**Comment by mccabemj** [comment]
!important is not supported in React
