### ISSUE TITLE
Fix React.PropTypes to PropTypes.

### ISSUE THREAD

**Issue by flashua** [abdennour/react-csv#17]
Recent changes in React makes metaProps.js cause a error/warning.
Suggestion to replace React.PropTypes to PropTypes trough importing separate React npm module 'prop-types' 

![metaprops](https://cloud.githubusercontent.com/assets/1665627/25149040/55ba69c4-247d-11e7-826f-30303f031daa.png)
@abdennour

**Comment by abdennour** [comment]
Thanks @flashua  : Your pull-request #18 was merged , then, this issue is fixed.

**Comment by abdennour** [comment]
This issue is now fixed with  the NPM release  `1.0.8` .
