### ISSUE TITLE
Unable to use with Webpack

### ISSUE THREAD

**Issue by ingro** [abdennour/react-csv#2]
Hello! I was trying to use your library with webpack but I get this warning:

```
Warning in ./~/react-csv/index.js
Critical dependencies:
1:17-32 the request of a dependency is an expression
 @ ./~/react-csv/index.js 1:17-32
```

which led to this error in the browser:
```
Uncaught Error: Cannot find module 'lib/'.
```

If I manually change `index.js` from this:

```javascript
module.exports = require(`lib`);
```

to this:

```javascript
module.exports = require(`./lib/index`);
```

it seems to work fine!

**Related**: it seems that `x-object`, which is a depdency of `react-csv`, is not compiled with babel, so it gives error when I try to minify my bundle with `uglifyjs`:

```
SyntaxError: Unexpected token: operator (>) [./~/x-object/safe.js:2,0]
```

Do you think that these problems could be fixed? Thank you.

**Comment by anwari32** [comment]
Hello, I think I've met the same thing with ingro up there. Is there any chance fixing that up? Thanks.

**Comment by abdennour** [comment]
Thank you for reporting this bug. I will be working on it ASAP .

**Comment by abdennour** [comment]
@anwari32  and @ingro  : I am really grateful for reporting this bug.. Hope It is now fixed and published in NPM . Please, let me know if you are facing any other issue
