### ISSUE TITLE
Output has non-printable chars

### ISSUE THREAD

**Issue by AnishJoseph** [abdennour/react-csv#22]
When i export a csv file i get 3 unprintable chars in the beginning of the file - hex values are ef, bb and bf. Am using chrome Version 57.0.2987.133 (64-bit) on OSX. I am using react-csv version 1.0.8
I notice in core.js the following function 
```javascript 
var buildURI = exports.buildURI = function buildURI(data, headers, separator) {
  return encodeURI('data:text/csv;charset=utf-8,\uFEFF' + toCSV(data, headers, separator));
};
```
If i remove the \uFEFF, as given below then the output is as expected without the non-printable chars. 
```javascript
var buildURI = exports.buildURI = function buildURI(data, headers, separator) {
  return encodeURI('data:text/csv;charset=utf-8,' + toCSV(data, headers, separator));
};
```
Not sure what the issue is.

**Comment by jimulle** [comment]
I see the same behavior as @AnishJoseph. What is the reason for the `\uFEFE`?

**Comment by nicoleivanov** [comment]
Going to comment this here as well, just in case anyone else is following this.  @jimulle  I just tried to implement the simple example download link and data, and I am having this issue of the 3 unreadable characters appearing in the first cell of the document when it opens in excel from Chrome. Do you know how I can fix this?  It works just fine through the link in the examples page http://elegance.abdennoor.com/react-csv/ so I'm not sure why it's not working for me.

**Comment by mccabemj** [comment]
@nicoleivanov are you using the latest version, since the fix above?

**Comment by nicoleivanov** [comment]
@mccabemj I believe I was, but I'm no longer using react-csv, so this isn't an issue for me anymore.  Thanks!

**Comment by pepijnolivier** [comment]
@nicoleivanov Care to share what you're using instead ?

**Comment by AnishJoseph** [comment]
That project died.  😔

**Comment by nicoleivanov** [comment]
@pepijnolivier I just made my own implementation.  No library, sorry!

**Comment by monossido** [comment]
Solved by adding 
`uFEFF={false}`
