### ISSUE TITLE
Module not found: Error: Cannot resolve module 'prop-types' in ...node_modules/react-csv/lib

### ISSUE THREAD

**Issue by mateodelnorte** [abdennour/react-csv#27]
Getting the following on an install and basic usage from Readme. 

```
[1] ERROR in ./~/react-csv/lib/metaProps.js
[1] Module not found: Error: Cannot resolve module 'prop-types' in /Users/mateodelnorte/development/dotbc/dotbc-queue-site/node_modules/react-csv/lib
[1]  @ ./~/react-csv/lib/metaProps.js 12:17-38
[1] webpack: Failed to compile.
```

**Comment by RBIII** [comment]
Getting this error as well

**Comment by abdennour** [comment]
DO NOT worry guys ! I will look at it.

**Comment by iyasto** [comment]
you need prop-types module.
`npm install --save prop-types`

**Comment by ashutoshkumarsingh** [comment]
i can't install the prop-types using this command `npm install --save prop-types`

**Comment by CatalinaCampos** [comment]
@ashutoshkumarsingh is the error fixed?

**Comment by elpagano** [comment]
I have the same error .

**Comment by carlosnani** [comment]
Same error here and npm install --save prop-types not worked.

**Comment by Ru-1218** [comment]
I worked npm install --save prop-types

**Comment by Ru-1218** [comment]
I worked npm install --save prop-types

nodejs=v10.19.0
npm=6.14.4

**Comment by ashekelahi** [comment]
I installed prop-types, but the error is still occurred...

**Comment by TrendyDeveloper** [comment]
Has anyone find an issue , I got stuck

**Comment by TrendyDeveloper** [comment]
I finally find it !
go to Run and Debug tab ( or tap ctrl+Shift+D)
in the drop-down menu choose : 'Run current file '
it should work without problem now

**Comment by daltoncirhuza9** [comment]
can't install the prop-types using this command npm install --save prop-types
it shows me this:
npm ERR! path /home/ashu/Documents/Ashu/Tech/Projects/React/demo/node_modules/prop-types/package.json
npm ERR! code ELOOP
npm ERR! errno -40
npm ERR! syscall open
npm ERR! ELOOP: too many symbolic links encountered, open '/home/ashu/Documents/Ashu/Tech/Projects/React/demo/node_modules/prop-types/package.json'

npm ERR! A complete log of this run can be found in:
npm ERR! /home/ashu/.npm/_logs/2018-06-05T06_58_55_705Z-debug.log

what could be the solution for this

**Comment by jojonah1812** [comment]
Same error here too.

**Comment by Svaught598** [comment]
Getting this issue as well. Trying to find a workaround now.

**Comment by codeyourwayup** [comment]
> prop-types

this works! I was installing the  "react-shadow-root": "^6.2.0", but webpack gives me this error.

**Comment by rasangalk** [comment]
> you need prop-types module. `npm install --save prop-types`

This resolve the issue. thanks buddy!

**Comment by Haritsinh** [comment]
> i can't install the prop-types using this command `npm install --save prop-types` it shows me this: npm ERR! path /home/ashu/Documents/Ashu/Tech/Projects/React/demo/node_modules/prop-types/package.json npm ERR! code ELOOP npm ERR! errno -40 npm ERR! syscall open npm ERR! ELOOP: too many symbolic links encountered, open '/home/ashu/Documents/Ashu/Tech/Projects/React/demo/node_modules/prop-types/package.json'
> 
> npm ERR! A complete log of this run can be found in: npm ERR! /home/ashu/.npm/_logs/2018-06-05T06_58_55_705Z-debug.log

Try `npm install --save prop-types --legacy-peer-deps` it will ignore the version error if you do that.

**Comment by YasinCap** [comment]
> you need prop-types module. `npm install --save prop-types`

you are a big legend my guy, a very big legend!
