### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by kunegun** [abdennour/react-csv#3]
Hi, great work @abdennour 

It would be great, if you can config the csv, for example, can change the separator, I need it would be a semi-colon (;), to then open in excel.

**Comment by abdennour** [comment]
@kunegun : Thank you for your feedback .  I will be working on this feature.

**Comment by abdennour** [comment]
This feature is now supported since RELEASE `1.0.1` .

Thank you @kunegun  .

**Comment by ketankanhasoft** [comment]
remove double quotes form CSV???

**Comment by ajiejot** [comment]
when I used `seperator` the output for ` array of objects` is messed up

**Comment by roniceyemeli** [comment]
extract nested arrays for the csv file could be nice 💯
