### ISSUE TITLE
'CSVDownload' is defined but never used

### ISSUE THREAD

**Issue by isaklafleur** [abdennour/react-csv#34]
Hello! Thanks you for developing such a great component!

I get this warning, because I only uses CSVLink, but if I remove CSVDownload in the import statment it does not work. Isn't it better you insert CSVDownload comp into CSVLink instead so it is not need to have as an import statement?

**Comment by tfazekas** [comment]
Hi! 

Just make sure you import it in the right way.

```import { CSVLink } from 'react-csv';```

**Comment by mriccid** [comment]
@isaklafleur could you please provide an example of the code that's causing this problem for you?

**Comment by mccabemj** [comment]
@isaklafleur is this still an issue or can it be closed?
