### ISSUE TITLE
Disable before async data load

### ISSUE THREAD

**Issue by krvajal** [abdennour/react-csv#35]
Is there a way to disable the link until I get my data from the server?

**Comment by abhinavjuneja** [comment]
I am also facing the same issue

**Comment by abdennour** [comment]
Yep! there is

**Comment by krvajal** [comment]
Can you elaborate on that?

**Comment by abdennour** [comment]
Read more about "onClick" props in README.
I think you need this example (already copied from README):

```sh
import {CSVLink} from 'react-csv';

<CSVLink data={data}
  asyncOnClick={true}
  onClick={(event, done) => {
      axios.post('/spy/user').then(() => {
        done(); // REQUIRED to invoke the logic of component
      });
  }}>
    Download me
</CSVLink>
```

**Comment by abdennour** [comment]
Sorry! I just got your case now. Let me think about it

**Comment by abdennour** [comment]
Currently, `CSVLink` is available after having the `data` ready.
Hence, you should handle this case in your application as following:
-Initially, Render button <Generate Report>.
- When the user clicks the button, you communicate with your API and you make the button in the loading state.
- Once data/response is ready, unmount the button <Generate Report> and mount the `CSVLink` <Download Report>.

**Comment by mccabemj** [comment]
@krvajal as @abdennour said, you can do a generate button. Or if your just waiting for the source data from an external source to download this can be done by just hiding the button until you have data

```
{
  this.props.sourceData ? 
    <CSVLink data={this.props.sourceData} />
  : null
}
```
