### ISSUE TITLE
Loading data asynchronously

### ISSUE THREAD

**Issue by arvinsim** [abdennour/react-csv#39]
Currently the data needs to be passed immediately to the component.

Is there a way to load data asynchronously?

**Comment by tfazekas** [comment]
Hi! 

Don't render the component till the data is not arrived.

Try something like this:
```
{this.props.data
     ?
        <CSVLink filename={`${Moment().format('YYYY-MM-DD_HH:mm:ss')}_data.csv`} data=
             {this.props.data}>
                  Fees CSV
         </CSVLink>
      : <button className="btn btn-primary btn-margin-left">
                  <i className="fa fa-refresh" /> No data yet
        </button>}
```

**Comment by coffenbacher** [comment]
@tfazekas at least for me, what I want to do is not retrieve the data until the link is fired, I don't want to pull it into memory unless it's required

**Comment by pcegarra** [comment]
My solution:
I have two buttons:

```
                            <FlatButton
                                onClick={this.onClickCsv}/>
                            <CSVLink ref="csv" data={csvData} style={{display:'none'}}/>
```


Then I load my data from the server and when it is loaded I call:
```
 let btn = this.refs.csv;
btn.link.click();
```

**Comment by dixitk13** [comment]
@coffenbacher this is what I tried and it works for me: (I use React+Redux)
the data is not fetched until the link is clicked and its not in memory. Once clicked it fetches, and reset's again. 

P.S: This is what @christianallred suggests in the [initial comment](https://github.com/abdennour/react-csv/issues/72#issuecomment-376650504) as well, using react state. 

Made a stateless component like this: 
```
const CSVButton = ({ data, fetchCSVData, fileName }) => {
  
  if (_.isEmpty(data)) {
    return (
      <span onClick={fetchCSVData} className="csv-download">
        CSV <Icon icon="download" />
      </span>
    )
  } else {
    return (
      <CSVDownload
        className="csv-download"
        target="_self"
        filename={fileName}
        data={data}
      />
    )
  }
}
```

the <b>fetchCSVData</b> action, fetches the data in async mode, and dispatches two actions using one action <b>receiveCSVDataAndReset</b>. one for setting the data field and other which un-sets/resets the data field. 

```
export const receiveCSVDataAndReset = (csvRunData) => async (dispatch) => {
  dispatch(receiveCSVData(csvRunData))
  // reset's it to remove the CSVDownload from DOM
  dispatch(receiveCSVData([]))
}

```

What really happens is, the state change triggers the reload of the stateless component and <b>CSVDownload</b> is rendered in the DOM to initiate the download functionality. The state is reset then to remove the specific element out of the DOM

**Comment by mungojam** [comment]
It would be great if this were supported natively by allowing a function to be passed for the data prop

**Comment by ccollins1544** [comment]
This seemed way over complicated just to get data asynchronously and exported with a custom filename. The **CSVDownload** is kind of useless without being able to set a **filename** property. Anyways here's my workaround I had to combine multiple solutions to get it working for me, 

`
// Button Component 
import React from "react";
import { CSVLink } from "react-csv";

const CSVButton = React.forwardRef((props, ref) => {
  let { data, fetchCSVData, filename } = props; 
  if (data && data.length > 0) {
    return (
      <CSVLink
        ref={ref}
        className="btn btn-secondary"
        target="_self"
        filename={filename}
        data={data}
      />
    )
  } else {
    return (
      <button onClick={fetchCSVData} className="btn btn-primary" >
        Export Filtered
      </button>
    )
  }
});

export { CSVButton };

// Table Component 
// ... ton of code ... 

const [ preparedData, setPreparedData ] = React.useState([]);
const csvBtn = React.useRef();
  
return (
<>
<CSVButton 
	ref={csvBtn}
	data={preparedData}
	fetchCSVData={async () => {
	  const response = await fetchFiltered(filters);
	  setPreparedData(response);

	  await csvBtn.current.link.click();
	  setTimeout(() => setPreparedData([]), 1500);
	}}
	filename={`${new Date().toISOString().replace(/\..+/, '').replace(/-/g, '').replace(/:/g, '').replace(/T/, '-')}.csv`}
 />
 // ... table code starts here ... 
 
// Main App Page Component
// ... ton of code ...

const fetchFiltered = async (filters) => {
    return await API.getFilteredTable(filters).then(response=>(response.data));
};
  
// ... ton of code ...

return (
<Wrapper className="App" id="main-container">
  <SectionRow id="main-section">
	<Col size="lg-12">
	  <h1>Page Title</h1>
	</Col>
	<Col size="lg-12">
	  <button onClick={resetData}>Reset Data</button>
	  <Table
		columns={columns}
		data={data}
		updateMyData={updateMyData}
		skipReset={skipResetRef.current}
		fetchFiltered={fetchFiltered}
	  />
	</Col>
  </SectionRow>
</Wrapper>
);

export default MyPage;
`

**Comment by MeshalKhalid** [comment]
It would much better if you use react hooks to handle the situation ...


`let [ csvData , setCSVData] = useState([])
`
```

<CSVLink
    data={csvData}
    filename='file.csv'
    onClick={async event => {
        try {
		let { data } = await something()
		setCSVData(data)
		}
      catch (error) {
 	// handle error
	}
}}>

dowload me !


</CSVLink>
```

**Comment by igortas** [comment]
Mine implementation:

useEffect hooks react on change in the data they u will fetch from some API. The button is part of other component.
download is simple function which read blob data, the blob can be extract with the ref, as under the hood the csv component is simple a href, or in my case, the buildURI fnction returns the blob:http link.

```
 useEffect(() => {
    function downloadCsv() {
      download(csvRef.current.buildURI(data), `filename_${date}.csv`);
    }
    downloadCsv();
  }, [data, date]);

  return (
    <CSVLink
      ref={csvRef}
      filename={`${filename}.csv`}
      headers={headers}
      data={data}
    />
  );
```

```
fetch(url).then(function (t) {
    return t.blob().then((b) => {
      const a = document.createElement('a');
      a.href = URL.createObjectURL(b);
      a.setAttribute('download', filename);
      a.click();
    });
  });
```

**Comment by tom-wagner** [comment]
The following article lays out how it was done in the old `this.setState()` days, however the callback on `setState` doesn't exist any more. Some options exist on StackOverflow, but they don't seem very good

https://www.cluemediator.com/loading-data-asynchronously-and-download-csv-using-react-csv
https://stackoverflow.com/questions/56247433/how-to-use-setstate-callback-on-react-hooks

Still searching
