### ISSUE TITLE
Elements with commas not supported

### ISSUE THREAD

**Issue by quintezkiller** [abdennour/react-csv#4]
When downloading a file where one of the elements may contain a comma, the file is downloaded incorrectly unless a custom separator is provided that is not a comma. The problem with this is that the file would no longer be a CSV.

I believe the problem would be resolved by updating your joiner() function in src/core.js to be:
`export const joiner = ((data,separator = ',') =>
 data.map((row, index) => row.map((element) => "'" + element + "'").join(separator)).join(`\n`)
);`

**Comment by quintezkiller** [comment]
I have a pull request open that resolves this problem.

**Comment by abdennour** [comment]
Great.. I am reviewing it.
