### ISSUE TITLE
null is downloaded as "null"

### ISSUE THREAD

**Issue by HenrikBechmann** [abdennour/react-csv#43]
like:

"2","null",3

should be 

"2",, "3"

or better

2,,3

**Comment by jimulle** [comment]
@HenrikBechmann, I completely see what you are saying here... I think a good solution would be for this to be a prop, default current behavior of exporting nulls as `"2","null",3` then the prop could allow an option for nulls to be mapped to something else (like `''` or `0` or whatever makes sense for the specific use case).

**Comment by jimulle** [comment]
Actually, there is a pull request for this exact issue sitting in error status (https://github.com/abdennour/react-csv/pull/41)
