### ISSUE TITLE
Component worked earlier in Chrome and now it fails

### ISSUE THREAD

**Issue by Kirbypnc** [abdennour/react-csv#44]
I had this component working earlier and now anytime I click the CSVLink it fails in Chrome. The same Download: Failed - Network Error. 

I have stripped the code back to the basic: <CSVLink data={this.state.report}>Download Report</CSVLink> and that fails as well.

**Comment by mickbalaban** [comment]
I ran into the same issue trying to export csv file with 40K rows. Thanks to this post on stackoverflow I was able to patch the code and make it work again: https://stackoverflow.com/a/39389497/8644750

**Comment by mriccid** [comment]
@mickbalaban are you able to provide an example of the network error that you get? I suspect it's a problem of the href being too long for such a large dataset but I'd like to confirm that before I create a PR with the fix.

**Comment by mickbalaban** [comment]
I created a quick example here: https://codesandbox.io/s/k2479pl5yr

Currently with 25000 rows of data it fails with network error. If you make the data array shorter, it will export csv successfully.

I hope that helps.

**Comment by huzaifarif** [comment]
I can confirm with increasing number of rows this fails on chrome but works on firefox (however takes a long time to start download after clicking on download).
I too resolved this using blob object in href as @mickbalaban

**Comment by clarali210** [comment]
When will this be implemented into a release? Thanks.

**Comment by rodrigomata** [comment]
+1

**Comment by mriccid** [comment]
react-csv@1.0.14 fixes this issue 👍
