### ISSUE TITLE
Remove `.babelrc` file from published npm package

### ISSUE THREAD

**Issue by denizs** [abdennour/react-csv#55]
Hey there!
First of all - thank you for this awesome package! 👍 
For the past two days, I've been struggling to get `react-csv` acting nicely with our project. More specifically, `npm install`s were throwing out error messages.
Finally, I figured out that you include your sample `.babelrc` file in your npm package, causing babel loader to adapt it. 😆

**Comment by abdennour** [comment]
Hello @denizs. Thank you for reporting the issue. We will add .babelrc in .npmignore

**Comment by abdennour** [comment]
1.0.11 contains the fix. 
Warm Regards

**Comment by denizs** [comment]
@abdennour no worries and thanks a lot 👍 :)
