### ISSUE TITLE
Export Button

### ISSUE THREAD

**Issue by farminf** [abdennour/react-csv#59]
Hi,

How can have a button which onClick exports the CSV?

**Comment by farminf** [comment]
I tried something like this and it is working, but is it the correct way?
`<CSVLink
                    data={this.props.transactions}
                    filename={"familyfinance" + moment().unix() + ".csv"}>
                    <Button
                        className={classes.button}
                        raised
                        color="primary">
                        Download CSV
                    </Button>
                </CSVLink>`

**Comment by mriccid** [comment]
It entirely depends on your `<Button>` component, but I would say that if the code you have provided above is working then I would go with it. 

Would you be interested in having more control over the HTML output of `<CSVLink>` so that perhaps you could have a `<button>` rather than an `<a>`?

**Comment by vvav3** [comment]
Your way absolutely works! onClick directly in CSVLink fired only after empty download. I think this should be mentioned in readme.

**Comment by farminf** [comment]
Yes, in fact it's working and that's fine for me. Anyway, I guess it can be useful to have more control over HTML part. Thanks.

**Comment by likohank** [comment]
<CSVLink
        className="btn btn-primary"
        filename={"Time Detail Report.csv"}
        data={data}
>

I think you mean this,"className="btn btn-primary""
