### ISSUE TITLE
Allowing numerical 0 entries

### ISSUE THREAD

**Issue by Danieth** [abdennour/react-csv#6]
I noticed that exports on objects including the numerical value `0` would have the `0`'s converted to `""`

I identified the line of code that's causing this. https://github.com/abdennour/react-csv/blob/master/src/core.js#L18

The boolean check is going to cast the numerical `0` to false.`NaN`, `false`, `null`, & `undefined` are also falsy - I could see how not allowing them could lead to confusion.

Currently, the string `"0"` on objects would not get cast. Also, an array of _any_ values will pass into the CSV without being cast.

What is the expected behavior? I'm willing to open a pull-request with the expected behavior - provided it allows for numerical 0's to be passed in on objects.

**Comment by abdennour** [comment]
Great catch.. Also `""` empty string is considered as falsy value .

**Comment by abdennour** [comment]
OK .. @Danieth  I welcome your pull-request : So, Please,  let's change the line 18: 

```js
   object[header] ? object[header] : ''))]
```

by 

```js
   String(object[header]) ? object[header] : ''))]
```

**Comment by abdennour** [comment]
RELEASE 1.0.5 is the  NPM release associated to this issue. 
Many thanks @Danieth .
