### ISSUE TITLE
Add a title to a sheet

### ISSUE THREAD

**Issue by stephanemombuleau** [abdennour/react-csv#61]
Hi,

I'd like to be able to generate a CSV with my columns and values, but I'd like to set a title header, something that would be centered on the first row and colspanned to the size of the actual columns.

In my case, I'm exporting charts to CSV. So it outputs the datatable of the chart, which is fine. But there are several charts and with the data only, it's sometimes hard to understand what the sheet is about. Say I apply a filter (let's say "date") to my "Distinct visitors by Country" chart and then export it, I'd like it to output something like that:

![react-csv-feature](https://user-images.githubusercontent.com/3513099/35732840-4a44d520-081b-11e8-83d8-7bebdc7eeb16.PNG)

Of course, the filename could be enough, but we don't always only want to rely on that.

Do you think this could be an interesting enhancement? I could look into it and open a PR.

**Comment by mriccid** [comment]
If those first two rows were present the CSV file would not be valid. This seems like a use case that would be satisfied by outputting an XLS file rather than CSV, but I don't think XLS use cases should be the concern of this component. 

If there's enough interest, perhaps it would be worth creating a separate component to export to Excel

**Comment by stephanemombuleau** [comment]
You're right that it isn't valid CSV, and rather a XLS use case, silly me. This is indeed not the concern for this.  Thanks for the quick feedback!

**Comment by mriccid** [comment]
Interestingly, I think that a lot of the time the CSV outputted by this component would end up in Excel so perhaps it's worthy of more discussion. Thanks for the idea and your contribution.

**Comment by joshuafernandes1996** [comment]
is there a workaround?
