### ISSUE TITLE
Failed-Network Error while downloading larger data

### ISSUE THREAD

**Issue by suprajareddy11** [abdennour/react-csv#62]
In the data property, am setting up array of big data size of around 16995 items. Where each array item is having around 16 properties/attributes. I am setting the component as shown below:
<CSVLink
                      data={this.state.myData}
                      filename="download.csv"
                      className="text-white"
                      style={{'textDecoration': 'none'}}
                      target="_blank" />

here this.state.myData is having 16995 items and each item is holding around 16 properties.

Kindly suggest!

**Comment by mriccid** [comment]
This looks like a duplicate of https://github.com/abdennour/react-csv/issues/44

**Comment by mriccid** [comment]
react-csv@1.0.14 fixes this issue 👍
