### ISSUE TITLE
Ability to define callback/capture event

### ISSUE THREAD

**Issue by rlreamy** [abdennour/react-csv#64]
We want to capture when a user downloads information from our application.  However, it appears there isn't currently a way to capture the click event.

**Comment by abdennour** [comment]
Greeting @rlreamy  , the new feature with developed and the related PR #66  is now under review, once it is merged, me or @mriccid  will release the updated NPM package.

Again, Thank you for this suggestion.

**Comment by MooreDevelopment** [comment]
This would be very useful to me. Asking the same as standingwave. Any chance of this being merged? I need to be able to do an onClick for this button.

**Comment by Domino987** [comment]
I could use this as well if the PR could be merged.

**Comment by abdennour** [comment]
@Domino987 I will merge PR. BTW, who wants to maintain this project with me ?
