### ISSUE TITLE
Problem with jsnext:main in package.json

### ISSUE THREAD

**Issue by yinyihui** [abdennour/react-csv#65]
Hi, I got a problem with the jsnext:main field.When I use webpack dev tool ‘eval’ to start a devserver,this field will point to src/index.js,but it can not pass the eslint rules. The eslint and babel configuration just like below:
	"babel": {
		"presets": [
			[
				"env",
				{
					"es2015": {
						"modules": false
					}
				}
			],
			"react",
			"stage-0"
		],
		"env": {
			"production": {
				"only": [
					"app"
				],
				"plugins": [
					"transform-decorators-legacy",
					"transform-react-remove-prop-types",
					"transform-react-constant-elements",
					"transform-react-inline-elements"
				]
			},
			"test": {
				"plugins": [
					"transform-es2015-modules-commonjs",
					"dynamic-import-node"
				]
			}
		},
		"plugins": [
			"transform-decorators-legacy", [
				"import",
				{
					"libraryName": "antd",
					"style": "css"
				}
			]
		]
	},
	"postcss": {
		"plugins": []
	},
	"eslintConfig": {
		"parser": "babel-eslint",
		"extends": "airbnb",
		"env": {
			"browser": true,
			"node": true,
			"jest": true,
			"es6": true
		},
		"plugins": [
			"react"
		],
		"globals": {
			"Highcharts": true,
			"_config": true
		},
		"parserOptions": {
			"ecmaVersion": 6,
			"sourceType": "module",
			"ecmaFeatures": {
				"jsx": true
			}
		},
		"rules": {
			"no-param-reassign": 0,
			"prefer-const": 0,
			"import/newline-after-import": 0,
			"import/no-extraneous-dependencies": 0,
			"import/no-dynamic-require": 0,
			"import/no-named-as-default": 0,
			"import/no-webpack-loader-syntax": 0,
			"import/prefer-default-export": 0,
			"jsx-a11y/no-static-element-interactions": 0,
			"no-underscore-dangle": 0,
			"object-curly-spacing": 0,
			"react/forbid-prop-types": 0,
			"react/prefer-stateless-function": 0,
			"react/prop-types": 1,
			"react/jsx-filename-extension": [
				1,
				{
					"extensions": [
						".js",
						".jsx"
					]
				}
			]
		},
		"settings": {
			"import/resolver": {
				"webpack": {
					"config": "./internals/webpack/webpack.prod.babel.js"
				}
			}
		}
	}

but when i delete the jsnext:main field or change if to 'lib/index.js', it's fine.So plz help me to find the solution of use this in devtool of Webpack 2. Thx.

**Comment by mriccid** [comment]
Can you please provide some more information? Are you able to provide the eslint errors and warnings? I am having trouble seeing the relationship between this library and the config and errors you have mentioned above.

**Comment by yinyihui** [comment]
I have found the solution.Because the jsnext:main point to the source code and my webpack babel loader has exclued the node_modules dir.This is no more a problem.But I think the jsnext:main should not point to the source code. [https://github.com/jsforum/jsforum/issues/5]
