### ISSUE TITLE
Not working for custom object

### ISSUE THREAD

**Issue by gopikrisna007** [abdennour/react-csv#75]
How can i add custom field like change date format in my download file data ?
i am using rest api call data

**Comment by mriccid** [comment]
It sounds like you need to transform the data before passing it to the component e.g. change the date format of some value and then download the CSV

**Comment by mccabemj** [comment]
@gopikrisna007 as @mriccid said, its best to transform the data yourself before you pass through to react-csv. @abdennour can re-open the issue if this feature is road marked

**Comment by mccabemj** [comment]
#23 duplication
