### ISSUE TITLE
Issue with IE 11 "Object doesn't support property or method 'from'

### ISSUE THREAD

**Issue by Se0ng11** [abdennour/react-csv#82]
![image](https://user-images.githubusercontent.com/2733646/40594317-087ed41a-6261-11e8-997f-4f759edf6f07.png)

react-csv is not working on IE 11, have a look on the sample page

**Comment by BebopPailliotet** [comment]
I had the same problem and  installed babel-polyfill and it is working now.

**Comment by Se0ng11** [comment]
@BebopPailliotet   think not the same issue? as i installed babel-polyfill too

**Comment by refex** [comment]
I installed babel-polyfill, now I don't have this message anymore but still cannot download csvs. Also the console of IE11 shows no error.

**Comment by Se0ng11** [comment]
ok, solved the issue, just need to put
`require("babel-polyfill");`
