### ISSUE TITLE
Breaks with server-side rendering

### ISSUE THREAD

**Issue by Tomekmularczyk** [abdennour/react-csv#87]
I'm using [Nextjs](https://nextjs.org/) which is server-side rendering the app. When I use the library I get:

> { ReferenceError: Blob is not defined
>     at buildURI (/Users/praca/Desktop/Projekty/move-dashboard/node_modules/react-csv/lib/core.js:87:14)
>     at CSVLink.buildURI (/Users/praca/Desktop/Projekty/move-dashboard/node_modules/react-csv/lib/components/Link.js:44:29)
>     at CSVLink.render (/Users/praca/Desktop/Projekty/move-dashboard/node_modules/react-csv/lib/components/Link.js:78:22)
>     at processChild (/Users/praca/Desktop/Projekty/move-dashboard/node_modules/react-dom/cjs/react-dom-server.node.development.js:2204:18)
>     at resolve (/Users/praca/Desktop/Projekty/move-dashboard/node_modules/react-dom/cjs/react-dom-server.node.development.js:2061:5)
>     at ReactDOMServerRenderer.render (/Users/praca/Desktop/Projekty/move-dashboard/node_modules/react-dom/cjs/react-dom-server.node.development.js:2380:22)
>     at ReactDOMServerRenderer.read (/Users/praca/Desktop/Projekty/move-dashboard/node_modules/react-dom/cjs/react-dom-server.node.development.js:2354:19)
>     at renderToString (/Users/praca/Desktop/Projekty/move-dashboard/node_modules/react-dom/cjs/react-dom-server.node.development.js:2726:25)
>     at renderPage (/Users/praca/Desktop/Projekty/move-dashboard/node_modules/next/dist/server/render.js:275:26)
>     at Function.getInitialProps (pages/_document.jsx:14:0)

**Comment by Tomekmularczyk** [comment]
you can just simply do:
```js
<div>
  {typeof window !== 'undefined' &&  <CSVLink ... />}
</div>
```
but the point is to take use of server-side-rendering and free user from having to do any workarounds

**Comment by mccabemj** [comment]
#88 merged
