### ISSUE TITLE
Save As - CSVLink

### ISSUE THREAD

**Issue by globsecure** [abdennour/react-csv#92]
You can run the "Save As" option when CSVLink is clicked.

**Comment by mccabemj** [comment]
@globsecure can we have some more information about your request? What browser/OS are you using, and what exactly do you want to happen?

**Comment by globsecure** [comment]
@mccabemj  - Hello, I actually discovered the problem is actually on the Electron that automatically downloads it.

Solution:
```
nativefier --file-download-options '{\ "saveAs \": true}' --icon ....
```

**Comment by Sireeshak546** [comment]
@globsecure  can you give an example how to use above solution with CSVLink component. need native file downloader in chrome instead of auto download on button click.
