### ISSUE TITLE
Explicit export function

### ISSUE THREAD

**Issue by SimpleCookie** [abdennour/react-csv#95]
Personally, I would like to have a function to trigger the export, rather than a HTML `<a>` element.
Is this doable without using JavaScript to trigger a click?

**Comment by abdennour** [comment]
Hello @SimpleCookie , You are still able to leverage the business logic layer of this software without using React component. Here an example: 

```js
const { toCSV }  = require('react-csv/lib/core');
const csvString = toCSV(
   data, 
   headers,
   separator
);
```
Note, [src/core.js](https://github.com/abdennour/react-csv/blob/master/src/core.js) is the core library of this software and all its functions are available for public usage.
