### ISSUE TITLE
handleClick broken

### ISSUE THREAD

**Issue by fiddlerwoaroof** [abdennour/react-csv#98]
This calls to handleSyncClick and handleAsyncClick should be `this.handleSyncClick` and `this.handleAsyncClick`

https://github.com/abdennour/react-csv/blob/c5ac9aa8687333ac12a2b1a4a508de729d9ba1b4/src/components/Link.js#L65-L67

**Comment by abdennour** [comment]
Thank you @fiddlerwoaroof ! It should be now fixed since release **1.0.15-RC2**
